class Comentarios {
    var preguntaeventonombre = println("¿Cuál es el nombre del evento?")
    var preguntaeventotipo = println("¿De qué tipo es el evento? (taller|conferencia)")
    var preguntaeventoduracion = println("¿Cuántos días dura el evento?")
    var preguntaubicaciontipo = println("¿Cómo es el evento? (online|fisico)")
    var preguntaubicaciondireccion = println("¿Cuál es la direccion del evento?")
    var preguntausuarionombre = println("¿Cómo se llama el usuario?")
    var preguntausuariocorreo = println("¿Cuál es el correo electrónico del usuario?")
    var preguntausuariocontrasenia = println("¿Cuál es la contraseña del usuario?")
    var preguntarorganizadornombre = println("¿Cuál es el nombre del organizador?")
    var preguntaorganizadorcontacto = println("¿Cuál es el contacto del organizador?")
    var preguntainscripcionevento = println("¿A qué evento corresponde la inscripcion?")
    var preguntaorganizadornuevonombreevento = println("¿Cuál es el nuevo nombre del evento?")
    var preguntaorganizadornuevotipoevento = println("¿Cuál es el nuevo tipo del evento?")
    var preguntaorganizadornuevaduracionevento = println("¿Cuál es la nueva duración del evento?")
    var preguntaorganizadornuevaubicaciontipo = println("¿Cómo es el nuevo evento? (online|fisico)")
    var preguntaorganizadornuevaubicacionevento = println("¿Cuál es la nueva direccion del evento?")
    var preguntaorganizadorcancelarevento = println("¿Desea cancelar el evento? (si|no)")
}